-- autogenerated lush spec on Thu Sep 11 15:49:02 2025
-- Run :Lushify
-- then /Normal to find the Normal group and edit your fg & bg colors
local lush = require("lush")
local hsl = lush.hsl
local hsluv = lush.hsluv
---@diagnostic disable: undefined-global
local theme = lush(function(injected_functions)
	local sym = injected_functions.sym
	return {
		SpecialKey({ fg = "#555555", gui = "italic" }), -- SpecialKey     xxx cterm=italic gui=italic guifg=#555555
		sym("@string.escape.markdown")({ SpecialKey }), -- @string.escape.markdown xxx links to SpecialKey
		NonText({ fg = "#555555" }), -- NonText        xxx guifg=#555555
		EndOfBuffer({ NonText }), -- EndOfBuffer    xxx links to NonText
		Whitespace({ NonText }), -- Whitespace     xxx links to NonText
		SnacksDashboardDir({ NonText }), -- SnacksDashboardDir xxx links to NonText
		SnacksNotifierFooterDebug({ NonText }), -- SnacksNotifierFooterDebug xxx links to NonText
		SnacksNotifierBorderDebug({ NonText }), -- SnacksNotifierBorderDebug xxx links to NonText
		SnacksNotifierTitleDebug({ NonText }), -- SnacksNotifierTitleDebug xxx links to NonText
		SnacksNotifierIconDebug({ NonText }), -- SnacksNotifierIconDebug xxx links to NonText
		SnacksNotifierIconTrace({ NonText }), -- SnacksNotifierIconTrace xxx links to NonText
		SnacksNotifierTitleTrace({ NonText }), -- SnacksNotifierTitleTrace xxx links to NonText
		SnacksNotifierBorderTrace({ NonText }), -- SnacksNotifierBorderTrace xxx links to NonText
		SnacksNotifierFooterTrace({ NonText }), -- SnacksNotifierFooterTrace xxx links to NonText
		SnacksPickerUnselected({ NonText }), -- SnacksPickerUnselected xxx links to NonText
		SnacksPickerBufFlags({ NonText }), -- SnacksPickerBufFlags xxx links to NonText
		SnacksPickerPathHidden({ NonText }), -- SnacksPickerPathHidden xxx links to NonText
		SnacksPickerKeymapRhs({ NonText }), -- SnacksPickerKeymapRhs xxx links to NonText
		SnacksPickerPathIgnored({ NonText }), -- SnacksPickerPathIgnored xxx links to NonText
		SnacksPickerDir({ NonText }), -- SnacksPickerDir xxx links to NonText
		SnacksPickerTotals({ NonText }), -- SnacksPickerTotals xxx links to NonText
		SnacksPickerGitStatusIgnored({ NonText }), -- SnacksPickerGitStatusIgnored xxx links to NonText
		SnacksPickerGitStatusUntracked({ NonText }), -- SnacksPickerGitStatusUntracked xxx links to NonText
		NoiceLspProgressTitle({ NonText }), -- NoiceLspProgressTitle xxx links to NonText
		NoiceFormatLevelOff({ NonText }), -- NoiceFormatLevelOff xxx links to NonText
		NoiceFormatLevelTrace({ NonText }), -- NoiceFormatLevelTrace xxx links to NonText
		NoiceFormatLevelDebug({ NonText }), -- NoiceFormatLevelDebug xxx links to NonText
		NoiceFormatKind({ NonText }), -- NoiceFormatKind xxx links to NonText
		NoiceFormatEvent({ NonText }), -- NoiceFormatEvent xxx links to NonText
		SnacksWinKeySep({ NonText }), -- SnacksWinKeySep xxx links to NonText
		BlinkCmpGhostText({ NonText }), -- BlinkCmpGhostText xxx links to NonText
		Directory({ gui = "bold" }), -- Directory      xxx cterm=bold gui=bold
		MiniFilesDirectory({ Directory }), -- MiniFilesDirectory xxx links to Directory
		SnacksPickerDirectory({ Directory }), -- SnacksPickerDirectory xxx links to Directory
		TroubleFilename({ Directory }), -- TroubleFilename xxx links to Directory
		TroubleDirectory({ Directory }), -- TroubleDirectory xxx links to Directory
		IncSearch({ fg = "#191919", bg = "#bf8fb5", gui = "bold" }), -- IncSearch      xxx cterm=bold gui=bold guifg=#191919 guibg=#bf8fb5
		CurSearch({ IncSearch }), -- CurSearch      xxx links to IncSearch
		LazyH1({ IncSearch }), -- LazyH1         xxx links to IncSearch
		Search({ fg = "#bbbbbb", bg = "#65435e" }), -- Search         xxx guifg=#bbbbbb guibg=#65435e
		QuickFixLine({ Search }), -- QuickFixLine   xxx links to Search
		Substitute({ Search }), -- Substitute     xxx links to Search
		MatchParen({ Search }), -- MatchParen     xxx links to Search
		Sneak({ Search }), -- Sneak          xxx links to Search
		CocSearch({ Search }), -- CocSearch      xxx links to Search
		SnacksPickerSearch({ Search }), -- SnacksPickerSearch xxx links to Search
		SnacksPickerPickWin({ Search }), -- SnacksPickerPickWin xxx links to Search
		MoreMsg({ fg = "#819b69", gui = "bold" }), -- MoreMsg        xxx cterm=bold gui=bold guifg=#819b69
		Question({ MoreMsg }), -- Question       xxx links to MoreMsg
		LineNr({ fg = "#616161" }), -- LineNr         xxx guifg=#616161
		LineNrAbove({ LineNr }), -- LineNrAbove    xxx links to LineNr
		LineNrBelow({ LineNr }), -- LineNrBelow    xxx links to LineNr
		SignColumn({ LineNr }), -- SignColumn     xxx links to LineNr
		LspCodeLens({ LineNr }), -- LspCodeLens    xxx links to LineNr
		NeogitHunkHeader({ LineNr }), -- NeogitHunkHeader xxx links to LineNr
		LazyProgressTodo({ LineNr }), -- LazyProgressTodo xxx links to LineNr
		CocCodeLens({ LineNr }), -- CocCodeLens    xxx links to LineNr
		SnacksPickerTree({ LineNr }), -- SnacksPickerTree xxx links to LineNr
		SnacksPickerCol({ LineNr }), -- SnacksPickerCol xxx links to LineNr
		TroublePos({ LineNr }), -- TroublePos     xxx links to LineNr
		TroubleIndent({ LineNr }), -- TroubleIndent  xxx links to LineNr
		CursorLineNr({ fg = "#bbbbbb", gui = "bold" }), -- CursorLineNr   xxx cterm=bold gui=bold guifg=#bbbbbb
		TroubleIndentFoldClosed({ CursorLineNr }), -- TroubleIndentFoldClosed xxx links to CursorLineNr
		StatusLine({ fg = "#bbbbbb", bg = "#303030" }), -- StatusLine     xxx guifg=#bbbbbb guibg=#303030
		TabLine({ StatusLine }), -- TabLine        xxx links to StatusLine
		MsgSeparator({ StatusLine }), -- MsgSeparator   xxx links to StatusLine
		WinBar({ StatusLine }), -- WinBar         xxx links to StatusLine
		StatusLineTerm({ StatusLine }), -- StatusLineTerm xxx links to StatusLine
		StatusLineNC({ fg = "#cfcfcf", bg = "#242424" }), -- StatusLineNC   xxx guifg=#cfcfcf guibg=#242424
		TabLineFill({ StatusLineNC }), -- TabLineFill    xxx links to StatusLineNC
		WinBarNC({ StatusLineNC }), -- WinBarNC       xxx links to StatusLineNC
		StatusLineTermNC({ StatusLineNC }), -- StatusLineTermNC xxx links to StatusLineNC
		WinSeparator({ fg = "#616161" }), -- WinSeparator   xxx guifg=#616161
		VertSplit({ WinSeparator }), -- VertSplit      xxx links to WinSeparator
		Title({ fg = "#bbbbbb", gui = "bold" }), -- Title          xxx cterm=bold gui=bold guifg=#bbbbbb
		sym("@markup.heading")({ Title }), -- @markup.heading xxx links to Title
		SnacksDashboardHeader({ Title }), -- SnacksDashboardHeader xxx links to Title
		SnacksDashboardFooter({ Title }), -- SnacksDashboardFooter xxx links to Title
		SnacksWinBar({ Title }), -- SnacksWinBar   xxx links to Title
		FzfLuaTitle({ Title }), -- FzfLuaTitle    xxx links to Title
		SnacksDashboardTitle({ Title }), -- SnacksDashboardTitle xxx links to Title
		LazyCommitType({ Title }), -- LazyCommitType xxx links to Title
		SnacksPickerGitBranch({ Title }), -- SnacksPickerGitBranch xxx links to Title
		SnacksPickerGitType({ Title }), -- SnacksPickerGitType xxx links to Title
		NoiceCmdlinePrompt({ Title }), -- NoiceCmdlinePrompt xxx links to Title
		NoiceLspProgressClient({ Title }), -- NoiceLspProgressClient xxx links to Title
		NoiceFormatTitle({ Title }), -- NoiceFormatTitle xxx links to Title
		SnacksNotifierHistoryTitle({ Title }), -- SnacksNotifierHistoryTitle xxx links to Title
		Visual({ bg = "#404040" }), -- Visual         xxx guibg=#404040
		VisualNOS({ Visual }), -- VisualNOS      xxx links to Visual
		LspSignatureActiveParameter({ Visual }), -- LspSignatureActiveParameter xxx links to Visual
		SnippetTabstop({ Visual }), -- SnippetTabstop xxx links to Visual
		LazyButtonActive({ Visual }), -- LazyButtonActive xxx links to Visual
		TroublePreview({ Visual }), -- TroublePreview xxx links to Visual
		NoiceFormatConfirmDefault({ Visual }), -- NoiceFormatConfirmDefault xxx links to Visual
		BlinkCmpDocCursorLine({ Visual }), -- BlinkCmpDocCursorLine xxx links to Visual
		WarningMsg({ fg = "#b77e64" }), -- WarningMsg     xxx guifg=#b77e64
		DiagnosticWarn({ WarningMsg }), -- DiagnosticWarn xxx links to WarningMsg
		sym("@comment.warning")({ WarningMsg }), -- @comment.warning xxx links to WarningMsg
		NoiceCmdlinePopupBorderSearch({ WarningMsg }), -- NoiceCmdlinePopupBorderSearch xxx links to WarningMsg
		NoiceCmdlineIconSearch({ WarningMsg }), -- NoiceCmdlineIconSearch xxx links to WarningMsg
		gitcommitOverflow({ WarningMsg }), -- gitcommitOverflow xxx links to WarningMsg
		WildMenu({ fg = "#191919", bg = "#b279a7" }), -- WildMenu       xxx guifg=#191919 guibg=#b279a7
		SneakLabel({ WildMenu }), -- SneakLabel     xxx links to WildMenu
		Folded({ fg = "#a3a3a3", bg = "#353535" }), -- Folded         xxx guifg=#a3a3a3 guibg=#353535
		FoldColumn({ fg = "#616161", gui = "bold" }), -- FoldColumn     xxx cterm=bold gui=bold guifg=#616161
		CursorLineFold({ FoldColumn }), -- CursorLineFold xxx links to FoldColumn
		DiffAdd({ bg = "#232d1a" }), -- DiffAdd        xxx guibg=#232d1a
		sym("@diff.plus")({ DiffAdd }), -- @diff.plus     xxx links to DiffAdd
		diffAdded({ DiffAdd }), -- diffAdded      xxx links to DiffAdd
		NeogitDiffAddHighlight({ DiffAdd }), -- NeogitDiffAddHighlight xxx links to DiffAdd
		DiffChange({ bg = "#1d2c36" }), -- DiffChange     xxx guibg=#1d2c36
		sym("@diff.delta")({ DiffChange }), -- @diff.delta    xxx links to DiffChange
		diffChanged({ DiffChange }), -- diffChanged    xxx links to DiffChange
		DiffDelete({ bg = "#3e2225" }), -- DiffDelete     xxx guibg=#3e2225
		sym("@diff.minus")({ DiffDelete }), -- @diff.minus    xxx links to DiffDelete
		diffRemoved({ DiffDelete }), -- diffRemoved    xxx links to DiffDelete
		NeogitDiffDeleteHighlight({ DiffDelete }), -- NeogitDiffDeleteHighlight xxx links to DiffDelete
		DiffText({ fg = "#bbbbbb", bg = "#324757" }), -- DiffText       xxx guifg=#bbbbbb guibg=#324757
		Conceal({ fg = "#7f7f7f", gui = "bold,italic" }), -- Conceal        xxx cterm=bold,italic gui=bold,italic guifg=#7f7f7f
		LazyProp({ Conceal }), -- LazyProp       xxx links to Conceal
		LazyDimmed({ Conceal }), -- LazyDimmed     xxx links to Conceal
		SnacksPickerDimmed({ Conceal }), -- SnacksPickerDimmed xxx links to Conceal
		SpellBad({ fg = "#cb7a83", gui = "undercurl" }), -- SpellBad       xxx cterm=undercurl gui=undercurl guifg=#cb7a83
		CocSelectedText({ SpellBad }), -- CocSelectedText xxx links to SpellBad
		SpellCap({ fg = "#cb7a83", gui = "undercurl" }), -- SpellCap       xxx cterm=undercurl gui=undercurl guifg=#cb7a83
		SpellLocal({ SpellCap }), -- SpellLocal     xxx links to SpellCap
		SpellRare({ fg = "#cb7a83", gui = "undercurl" }), -- SpellRare      xxx cterm=undercurl gui=undercurl guifg=#cb7a83
		Pmenu({ bg = "#2c2c2c" }), -- Pmenu          xxx guibg=#2c2c2c
		PmenuKind({ Pmenu }), -- PmenuKind      xxx links to Pmenu
		PmenuExtra({ Pmenu }), -- PmenuExtra     xxx links to Pmenu
		BlinkCmpMenuBorder({ Pmenu }), -- BlinkCmpMenuBorder xxx links to Pmenu
		BlinkCmpMenu({ Pmenu }), -- BlinkCmpMenu   xxx links to Pmenu
		NoicePopupmenu({ Pmenu }), -- NoicePopupmenu xxx links to Pmenu
		PmenuSel({ bg = "#444444" }), -- PmenuSel       xxx guibg=#444444
		PmenuKindSel({ PmenuSel }), -- PmenuKindSel   xxx links to PmenuSel
		PmenuExtraSel({ PmenuSel }), -- PmenuExtraSel  xxx links to PmenuSel
		BlinkCmpMenuSelection({ PmenuSel }), -- BlinkCmpMenuSelection xxx links to PmenuSel
		NoicePopupmenuSelected({ PmenuSel }), -- NoicePopupmenuSelected xxx links to PmenuSel
		PmenuMatch({ gui = "bold" }), -- PmenuMatch     xxx cterm=bold gui=bold
		PmenuMatchSel({ gui = "bold" }), -- PmenuMatchSel  xxx cterm=bold gui=bold
		PmenuSbar({ bg = "#595959" }), -- PmenuSbar      xxx guibg=#595959
		BlinkCmpScrollBarGutter({ PmenuSbar }), -- BlinkCmpScrollBarGutter xxx links to PmenuSbar
		NoiceScrollbar({ PmenuSbar }), -- NoiceScrollbar xxx links to PmenuSbar
		PmenuThumb({ bg = "#848484" }), -- PmenuThumb     xxx guibg=#848484
		BlinkCmpScrollBarThumb({ PmenuThumb }), -- BlinkCmpScrollBarThumb xxx links to PmenuThumb
		NoiceScrollbarThumb({ PmenuThumb }), -- NoiceScrollbarThumb xxx links to PmenuThumb
		TabLineSel({ gui = "bold" }), -- TabLineSel     xxx cterm=bold gui=bold
		TroubleCount({ TabLineSel }), -- TroubleCount   xxx links to TabLineSel
		BufferCurrent({ TabLineSel }), -- BufferCurrent  xxx links to TabLineSel
		CursorLine({ bg = "#222222" }), -- CursorLine     xxx guibg=#222222
		CursorColumn({ CursorLine }), -- CursorColumn   xxx links to CursorLine
		MiniFilesCursorLine({ CursorLine }), -- MiniFilesCursorLine xxx links to CursorLine
		NeogitDiffContextHighlight({ CursorLine }), -- NeogitDiffContextHighlight xxx links to CursorLine
		TelescopeSelection({ CursorLine }), -- TelescopeSelection xxx links to CursorLine
		NoiceFormatProgressTodo({ CursorLine }), -- NoiceFormatProgressTodo xxx links to CursorLine
		LazyButton({ CursorLine }), -- LazyButton     xxx links to CursorLine
		SnacksPickerListCursorLine({ CursorLine }), -- SnacksPickerListCursorLine xxx links to CursorLine
		SnacksPickerPreviewCursorLine({ CursorLine }), -- SnacksPickerPreviewCursorLine xxx links to CursorLine
		FzfLuaFzfCursorLine({ CursorLine }), -- FzfLuaFzfCursorLine xxx links to CursorLine
		CocMenuSel({ CursorLine }), -- CocMenuSel     xxx links to CursorLine
		NoiceFormatConfirm({ CursorLine }), -- NoiceFormatConfirm xxx links to CursorLine
		ColorColumn({ bg = "#55392c" }), -- ColorColumn    xxx guibg=#55392c
		LspReferenceRead({ ColorColumn }), -- LspReferenceRead xxx links to ColorColumn
		LspReferenceText({ ColorColumn }), -- LspReferenceText xxx links to ColorColumn
		LspReferenceWrite({ ColorColumn }), -- LspReferenceWrite xxx links to ColorColumn
		NormalFloat({ bg = "#2c2c2c" }), -- NormalFloat    xxx guibg=#2c2c2c
		SnacksNormalNC({ NormalFloat }), -- SnacksNormalNC xxx links to NormalFloat
		SnacksNormal({ NormalFloat }), -- SnacksNormal   xxx links to NormalFloat
		MiniFilesNormal({ NormalFloat }), -- MiniFilesNormal xxx links to NormalFloat
		BlinkCmpDocBorder({ NormalFloat }), -- BlinkCmpDocBorder xxx links to NormalFloat
		BlinkCmpSignatureHelpBorder({ NormalFloat }), -- BlinkCmpSignatureHelpBorder xxx links to NormalFloat
		BlinkCmpDoc({ NormalFloat }), -- BlinkCmpDoc    xxx links to NormalFloat
		SnacksPickerBorder({ NormalFloat }), -- SnacksPickerBorder xxx links to NormalFloat
		LazyNormal({ NormalFloat }), -- LazyNormal     xxx links to NormalFloat
		TroubleNormalNC({ NormalFloat }), -- TroubleNormalNC xxx links to NormalFloat
		WhichKeyNormal({ NormalFloat }), -- WhichKeyNormal xxx links to NormalFloat
		NoiceSplit({ NormalFloat }), -- NoiceSplit     xxx links to NormalFloat
		NoicePopup({ NormalFloat }), -- NoicePopup     xxx links to NormalFloat
		SnacksNotifierMinimal({ NormalFloat }), -- SnacksNotifierMinimal xxx links to NormalFloat
		BlinkCmpDocSeparator({ NormalFloat }), -- BlinkCmpDocSeparator xxx links to NormalFloat
		BlinkCmpSignatureHelp({ NormalFloat }), -- BlinkCmpSignatureHelp xxx links to NormalFloat
		FloatBorder({ fg = "#797979" }), -- FloatBorder    xxx guifg=#797979
		MiniFilesBorder({ FloatBorder }), -- MiniFilesBorder xxx links to FloatBorder
		WhichKeyBorder({ FloatBorder }), -- WhichKeyBorder xxx links to FloatBorder
		NoiceSplitBorder({ FloatBorder }), -- NoiceSplitBorder xxx links to FloatBorder
		NoicePopupmenuBorder({ FloatBorder }), -- NoicePopupmenuBorder xxx links to FloatBorder
		NoicePopupBorder({ FloatBorder }), -- NoicePopupBorder xxx links to FloatBorder
		Cursor({ fg = "#191919", bg = "#c9c9c9" }), -- Cursor         xxx guifg=#191919 guibg=#c9c9c9
		TermCursor({ Cursor }), -- TermCursor     xxx links to Cursor
		CursorIM({ Cursor }), -- CursorIM       xxx links to Cursor
		NoiceCursor({ Cursor }), -- NoiceCursor    xxx links to Cursor
		FloatTitle({ fg = "#bbbbbb", bg = "#2c2c2c", gui = "bold" }), -- FloatTitle     xxx cterm=bold gui=bold guifg=#bbbbbb guibg=#2c2c2c
		FloatFooter({ FloatTitle }), -- FloatFooter    xxx links to FloatTitle
		MiniFilesTitleFocused({ FloatTitle }), -- MiniFilesTitleFocused xxx links to FloatTitle
		MiniFilesTitle({ FloatTitle }), -- MiniFilesTitle xxx links to FloatTitle
		WhichKeyTitle({ FloatTitle }), -- WhichKeyTitle  xxx links to FloatTitle
		RedrawDebugNormal({ gui = "reverse" }), -- RedrawDebugNormal xxx cterm=reverse gui=reverse
		Underlined({ gui = "underline" }), -- Underlined     xxx cterm=underline gui=underline
		sym("@markup.underline")({ Underlined }), -- @markup.underline xxx links to Underlined
		lCursor({ fg = "#191919", bg = "#7f7f7f" }), -- lCursor        xxx guifg=#191919 guibg=#7f7f7f
		TermCursorNC({ lCursor }), -- TermCursorNC   xxx links to lCursor
		Normal({ fg = "#bbbbbb", bg = "#191919" }), -- Normal         xxx guifg=#bbbbbb guibg=#191919
		ModeMsg({ Normal }), -- ModeMsg        xxx links to Normal
		Ignore({ Normal }), -- Ignore         xxx links to Normal
		NvimSpacing({ Normal }), -- NvimSpacing    xxx links to Normal
		SnacksNotifierDebug({ Normal }), -- SnacksNotifierDebug xxx links to Normal
		SnacksNotifierWarn({ Normal }), -- SnacksNotifierWarn xxx links to Normal
		SnacksNotifierInfo({ Normal }), -- SnacksNotifierInfo xxx links to Normal
		SnacksNotifierError({ Normal }), -- SnacksNotifierError xxx links to Normal
		SnacksDashboardNormal({ Normal }), -- SnacksDashboardNormal xxx links to Normal
		SnacksNotifierTrace({ Normal }), -- SnacksNotifierTrace xxx links to Normal
		SnacksInputNormal({ Normal }), -- SnacksInputNormal xxx links to Normal
		SnacksPickerIconFile({ Normal }), -- SnacksPickerIconFile xxx links to Normal
		TroubleIconFile({ Normal }), -- TroubleIconFile xxx links to Normal
		WhichKeyIconGrey({ Normal }), -- WhichKeyIconGrey xxx links to Normal
		NoiceConfirm({ Normal }), -- NoiceConfirm   xxx links to Normal
		NoiceCmdlinePopup({ Normal }), -- NoiceCmdlinePopup xxx links to Normal
		SnacksNotifierHistory({ Normal }), -- SnacksNotifierHistory xxx links to Normal
		Constant({ fg = "#8b8b8b", gui = "italic" }), -- Constant       xxx cterm=italic gui=italic guifg=#8b8b8b
		Character({ Constant }), -- Character      xxx links to Constant
		sym("@variable.builtin")({ Constant }), -- @variable.builtin xxx links to Constant
		sym("@constant.builtin")({ Constant }), -- @constant.builtin xxx links to Constant
		sym("@module")({ Constant }), -- @module        xxx links to Constant
		sym("@string.regexp")({ Constant }), -- @string.regexp xxx links to Constant
		sym("@character")({ Constant }), -- @character     xxx links to Constant
		sym("@markup.link")({ Constant }), -- @markup.link   xxx links to Constant
		sym("@constant.macro")({ Constant }), -- @constant.macro xxx links to Constant
		WhichKeyValue({ Constant }), -- WhichKeyValue  xxx links to Constant
		sym("@markup.raw")({ Constant }), -- @markup.raw    xxx links to Constant
		sym("@markup.link.url")({ Constant }), -- @markup.link.url xxx links to Constant
		MiniIconsPurple({ Constant }), -- MiniIconsPurple xxx links to Constant
		LazyReasonEvent({ Constant }), -- LazyReasonEvent xxx links to Constant
		LazyProgressDone({ Constant }), -- LazyProgressDone xxx links to Constant
		LazyLocal({ Constant }), -- LazyLocal      xxx links to Constant
		helpOption({ Constant }), -- helpOption     xxx links to Constant
		TroubleSource({ Constant }), -- TroubleSource  xxx links to Constant
		SnacksPickerAuEvent({ Constant }), -- SnacksPickerAuEvent xxx links to Constant
		WhichKeyIconPurple({ Constant }), -- WhichKeyIconPurple xxx links to Constant
		NoiceLspProgressSpinner({ Constant }), -- NoiceLspProgressSpinner xxx links to Constant
		Number({ fg = "#8b8b8b" }), -- Number         xxx guifg=#8b8b8b
		Float({ Number }), -- Float          xxx links to Number
		sym("@number")({ Number }), -- @number        xxx links to Number
		NvimNumber({ Number }), -- NvimNumber     xxx links to Number
		SnacksDashboardKey({ Number }), -- SnacksDashboardKey xxx links to Number
		SnacksPickerSelected({ Number }), -- SnacksPickerSelected xxx links to Number
		LazyCommitIssue({ Number }), -- LazyCommitIssue xxx links to Number
		SnacksPickerIdx({ Number }), -- SnacksPickerIdx xxx links to Number
		SnacksPickerBufNr({ Number }), -- SnacksPickerBufNr xxx links to Number
		SnacksPickerKeymapMode({ Number }), -- SnacksPickerKeymapMode xxx links to Number
		SnacksPickerGitIssue({ Number }), -- SnacksPickerGitIssue xxx links to Number
		SnacksPickerManSection({ Number }), -- SnacksPickerManSection xxx links to Number
		SnacksPickerRegister({ Number }), -- SnacksPickerRegister xxx links to Number
		SnacksPickerGitBranchCurrent({ Number }), -- SnacksPickerGitBranchCurrent xxx links to Number
		Boolean({ fg = "#bbbbbb", gui = "italic" }), -- Boolean        xxx cterm=italic gui=italic guifg=#bbbbbb
		sym("@boolean")({ Boolean }), -- @boolean       xxx links to Boolean
		Statement({ fg = "#bbbbbb", gui = "bold" }), -- Statement      xxx cterm=bold gui=bold guifg=#bbbbbb
		Conditional({ Statement }), -- Conditional    xxx links to Statement
		Repeat({ Statement }), -- Repeat         xxx links to Statement
		Label({ Statement }), -- Label          xxx links to Statement
		Keyword({ Statement }), -- Keyword        xxx links to Statement
		Exception({ Statement }), -- Exception      xxx links to Statement
		PreProc({ Statement }), -- PreProc        xxx links to Statement
		sym("@label")({ Statement }), -- @label         xxx links to Statement
		sym("@operator")({ Statement }), -- @operator      xxx links to Statement
		sym("@lsp.type.keyword")({ Statement }), -- @lsp.type.keyword xxx links to Statement
		WhichKey({ Statement }), -- WhichKey       xxx links to Statement
		sym("@keyword.conditional")({ Statement }), -- @keyword.conditional xxx links to Statement
		sym("@keyword.exception")({ Statement }), -- @keyword.exception xxx links to Statement
		sym("@keyword.return")({ Statement }), -- @keyword.return xxx links to Statement
		sym("@keyword.repeat")({ Statement }), -- @keyword.repeat xxx links to Statement
		sym("@keyword.operator")({ Statement }), -- @keyword.operator xxx links to Statement
		sym("@keyword.function")({ Statement }), -- @keyword.function xxx links to Statement
		sym("@keyword.coroutine")({ Statement }), -- @keyword.coroutine xxx links to Statement
		FzfLuaBufName({ Statement }), -- FzfLuaBufName  xxx links to Statement
		LazyReasonKeys({ Statement }), -- LazyReasonKeys xxx links to Statement
		sym("@markup.title.markdown")({ Statement }), -- @markup.title.markdown xxx links to Statement
		sym("@lsp.typemod.keyword.injected")({ Statement }), -- @lsp.typemod.keyword.injected xxx links to Statement
		Type({ fg = "#969696" }), -- Type           xxx guifg=#969696
		StorageClass({ Type }), -- StorageClass   xxx links to Type
		Structure({ Type }), -- Structure      xxx links to Type
		Typedef({ Type }), -- Typedef        xxx links to Type
		sym("@type")({ Type }), -- @type          xxx links to Type
		NvimNumberPrefix({ Type }), -- NvimNumberPrefix xxx links to Type
		NvimOptionSigil({ Type }), -- NvimOptionSigil xxx links to Type
		markdownCode({ Type }), -- markdownCode   xxx links to Type
		BlinkCmpLabelDetail({ Type }), -- BlinkCmpLabelDetail xxx links to Type
		BlinkCmpLabelDescription({ Type }), -- BlinkCmpLabelDescription xxx links to Type
		sym("@keyword.storage")({ Type }), -- @keyword.storage xxx links to Type
		sym("@markup.raw.markdown")({ Type }), -- @markup.raw.markdown xxx links to Type
		sym("@variable.parameter.vimdoc")({ Type }), -- @variable.parameter.vimdoc xxx links to Type
		helpSpecial({ Type }), -- helpSpecial    xxx links to Type
		BlinkCmpSource({ Type }), -- BlinkCmpSource xxx links to Type
		SnacksPickerAuGroup({ Type }), -- SnacksPickerAuGroup xxx links to Type
		Special({ fg = "#939393", gui = "bold" }), -- Special        xxx cterm=bold gui=bold guifg=#939393
		Tag({ Special }), -- Tag            xxx links to Special
		SpecialChar({ Special }), -- SpecialChar    xxx links to Special
		Debug({ Special }), -- Debug          xxx links to Special
		sym("@variable.parameter.builtin")({ Special }), -- @variable.parameter.builtin xxx links to Special
		sym("@string.special")({ Special }), -- @string.special xxx links to Special
		sym("@string.escape")({ Special }), -- @string.escape xxx links to Special
		sym("@character.special")({ Special }), -- @character.special xxx links to Special
		sym("@attribute.builtin")({ Special }), -- @attribute.builtin xxx links to Special
		sym("@function.builtin")({ Special }), -- @function.builtin xxx links to Special
		sym("@constructor")({ Special }), -- @constructor   xxx links to Special
		sym("@markup")({ Special }), -- @markup        xxx links to Special
		sym("@tag")({ Special }), -- @tag           xxx links to Special
		sym("@tag.builtin")({ Special }), -- @tag.builtin   xxx links to Special
		SnacksDashboardIcon({ Special }), -- SnacksDashboardIcon xxx links to Special
		SnacksDashboardFile({ Special }), -- SnacksDashboardFile xxx links to Special
		WhichKeyGroup({ Special }), -- WhichKeyGroup  xxx links to Special
		SnacksPickerPrompt({ Special }), -- SnacksPickerPrompt xxx links to Special
		sym("@markup.link.label")({ Special }), -- @markup.link.label xxx links to Special
		sym("@markup.list")({ Special }), -- @markup.list   xxx links to Special
		sym("@markup.math")({ Special }), -- @markup.math   xxx links to Special
		sym("@keyword.debug")({ Special }), -- @keyword.debug xxx links to Special
		SnacksDashboardDesc({ Special }), -- SnacksDashboardDesc xxx links to Special
		SnacksDashboardSpecial({ Special }), -- SnacksDashboardSpecial xxx links to Special
		LazyReasonPlugin({ Special }), -- LazyReasonPlugin xxx links to Special
		sym("@punctuation.special.markdown")({ Special }), -- @punctuation.special.markdown xxx links to Special
		SnacksPickerSpecial({ Special }), -- SnacksPickerSpecial xxx links to Special
		SnacksPickerSpinner({ Special }), -- SnacksPickerSpinner xxx links to Special
		SnacksPickerKeymapLhs({ Special }), -- SnacksPickerKeymapLhs xxx links to Special
		SnacksPickerIconEvent({ Special }), -- SnacksPickerIconEvent xxx links to Special
		SnacksPickerDiagnosticCode({ Special }), -- SnacksPickerDiagnosticCode xxx links to Special
		SnacksPickerTime({ Special }), -- SnacksPickerTime xxx links to Special
		SnacksPickerUndoSaved({ Special }), -- SnacksPickerUndoSaved xxx links to Special
		SnacksPickerIcon({ Special }), -- SnacksPickerIcon xxx links to Special
		SnacksPickerLspEnabled({ Special }), -- SnacksPickerLspEnabled xxx links to Special
		SnacksPickerGitStatus({ Special }), -- SnacksPickerGitStatus xxx links to Special
		SnacksPickerManPage({ Special }), -- SnacksPickerManPage xxx links to Special
		SnacksPickerGitDate({ Special }), -- SnacksPickerGitDate xxx links to Special
		TroubleCode({ Special }), -- TroubleCode    xxx links to Special
		TroubleIconDirectory({ Special }), -- TroubleIconDirectory xxx links to Special
		TroubleIconEvent({ Special }), -- TroubleIconEvent xxx links to Special
		NoiceFormatDate({ Special }), -- NoiceFormatDate xxx links to Special
		NoicePopupmenuMatch({ Special }), -- NoicePopupmenuMatch xxx links to Special
		SnacksNotifierHistoryDateTime({ Special }), -- SnacksNotifierHistoryDateTime xxx links to Special
		SpecialComment({ fg = "#686868" }), -- SpecialComment xxx guifg=#686868
		sym("@markup.link.url.markdown")({ SpecialComment }), -- @markup.link.url.markdown xxx links to SpecialComment
		markdownUrl({ SpecialComment }), -- markdownUrl    xxx links to SpecialComment
		LspInlayHint({ fg = "#7a6569", bg = "#222222" }), -- LspInlayHint   xxx guifg=#7a6569 guibg=#222222
		DiagnosticInfo({ fg = "#6099c0" }), -- DiagnosticInfo xxx guifg=#6099c0
		DiagnosticFloatingInfo({ DiagnosticInfo }), -- DiagnosticFloatingInfo xxx links to DiagnosticInfo
		DiagnosticVirtualLinesInfo({ DiagnosticInfo }), -- DiagnosticVirtualLinesInfo xxx links to DiagnosticInfo
		sym("@comment.note")({ DiagnosticInfo }), -- @comment.note  xxx links to DiagnosticInfo
		NotifyINFOTitle({ DiagnosticInfo }), -- NotifyINFOTitle xxx links to DiagnosticInfo
		NotifyINFOIcon({ DiagnosticInfo }), -- NotifyINFOIcon xxx links to DiagnosticInfo
		MiniIconsBlue({ DiagnosticInfo }), -- MiniIconsBlue  xxx links to DiagnosticInfo
		SnacksNotifierBorderInfo({ DiagnosticInfo }), -- SnacksNotifierBorderInfo xxx links to DiagnosticInfo
		SnacksNotifierFooterInfo({ DiagnosticInfo }), -- SnacksNotifierFooterInfo xxx links to DiagnosticInfo
		SnacksNotifierTitleInfo({ DiagnosticInfo }), -- SnacksNotifierTitleInfo xxx links to DiagnosticInfo
		NeogitNotificationInfo({ DiagnosticInfo }), -- NeogitNotificationInfo xxx links to DiagnosticInfo
		LazyInfo({ DiagnosticInfo }), -- LazyInfo       xxx links to DiagnosticInfo
		SnacksInputTitle({ DiagnosticInfo }), -- SnacksInputTitle xxx links to DiagnosticInfo
		SnacksInputBorder({ DiagnosticInfo }), -- SnacksInputBorder xxx links to DiagnosticInfo
		SnacksPickerLspAttachedBuf({ DiagnosticInfo }), -- SnacksPickerLspAttachedBuf xxx links to DiagnosticInfo
		WhichKeyIconBlue({ DiagnosticInfo }), -- WhichKeyIconBlue xxx links to DiagnosticInfo
		DiagnosticHint({ fg = "#b279a7" }), -- DiagnosticHint xxx guifg=#b279a7
		DiagnosticFloatingHint({ DiagnosticHint }), -- DiagnosticFloatingHint xxx links to DiagnosticHint
		DiagnosticVirtualLinesHint({ DiagnosticHint }), -- DiagnosticVirtualLinesHint xxx links to DiagnosticHint
		NotifyTRACETitle({ DiagnosticHint }), -- NotifyTRACETitle xxx links to DiagnosticHint
		NotifyTRACEIcon({ DiagnosticHint }), -- NotifyTRACEIcon xxx links to DiagnosticHint
		NotifyDEBUGTitle({ DiagnosticHint }), -- NotifyDEBUGTitle xxx links to DiagnosticHint
		NotifyDEBUGIcon({ DiagnosticHint }), -- NotifyDEBUGIcon xxx links to DiagnosticHint
		MiniIconsCyan({ DiagnosticHint }), -- MiniIconsCyan  xxx links to DiagnosticHint
		SnacksStatusColumnMark({ DiagnosticHint }), -- SnacksStatusColumnMark xxx links to DiagnosticHint
		SnacksInputIcon({ DiagnosticHint }), -- SnacksInputIcon xxx links to DiagnosticHint
		SnacksPickerGitStatusStaged({ DiagnosticHint }), -- SnacksPickerGitStatusStaged xxx links to DiagnosticHint
		WhichKeyIconCyan({ DiagnosticHint }), -- WhichKeyIconCyan xxx links to DiagnosticHint
		DiagnosticOk({ fg = "#819b69" }), -- DiagnosticOk   xxx guifg=#819b69
		DiagnosticFloatingOk({ DiagnosticOk }), -- DiagnosticFloatingOk xxx links to DiagnosticOk
		DiagnosticVirtualLinesOk({ DiagnosticOk }), -- DiagnosticVirtualLinesOk xxx links to DiagnosticOk
		MiniIconsGreen({ DiagnosticOk }), -- MiniIconsGreen xxx links to DiagnosticOk
		WhichKeyIconGreen({ DiagnosticOk }), -- WhichKeyIconGreen xxx links to DiagnosticOk
		DiagnosticVirtualTextError({ fg = "#de6e7c", bg = "#272020" }), -- DiagnosticVirtualTextError xxx guifg=#de6e7c guibg=#272020
		CocErrorVirtualText({ DiagnosticVirtualTextError }), -- CocErrorVirtualText xxx links to DiagnosticVirtualTextError
		NoiceFormatLevelError({ DiagnosticVirtualTextError }), -- NoiceFormatLevelError xxx links to DiagnosticVirtualTextError
		DiagnosticVirtualTextWarn({ fg = "#b77e64", bg = "#242120" }), -- DiagnosticVirtualTextWarn xxx guifg=#b77e64 guibg=#242120
		CocWarningVirtualText({ DiagnosticVirtualTextWarn }), -- CocWarningVirtualText xxx links to DiagnosticVirtualTextWarn
		NoiceFormatLevelWarn({ DiagnosticVirtualTextWarn }), -- NoiceFormatLevelWarn xxx links to DiagnosticVirtualTextWarn
		DiagnosticVirtualTextInfo({ fg = "#6099c0", bg = "#202223" }), -- DiagnosticVirtualTextInfo xxx guifg=#6099c0 guibg=#202223
		SnacksPickerToggle({ DiagnosticVirtualTextInfo }), -- SnacksPickerToggle xxx links to DiagnosticVirtualTextInfo
		NoiceFormatLevelInfo({ DiagnosticVirtualTextInfo }), -- NoiceFormatLevelInfo xxx links to DiagnosticVirtualTextInfo
		NoiceVirtualText({ DiagnosticVirtualTextInfo }), -- NoiceVirtualText xxx links to DiagnosticVirtualTextInfo
		DiagnosticVirtualTextHint({ fg = "#b279a7", bg = "#252024" }), -- DiagnosticVirtualTextHint xxx guifg=#b279a7 guibg=#252024
		DiagnosticVirtualTextOk({ fg = "#819b69", bg = "#212220" }), -- DiagnosticVirtualTextOk xxx guifg=#819b69 guibg=#212220
		DiagnosticSignError({ fg = "#de6e7c" }), -- DiagnosticSignError xxx guifg=#de6e7c
		SnacksNotifierIconError({ DiagnosticSignError }), -- SnacksNotifierIconError xxx links to DiagnosticSignError
		CocErrorSign({ DiagnosticSignError }), -- CocErrorSign   xxx links to DiagnosticSignError
		DiagnosticSignWarn({ fg = "#b77e64" }), -- DiagnosticSignWarn xxx guifg=#b77e64
		SnacksNotifierIconWarn({ DiagnosticSignWarn }), -- SnacksNotifierIconWarn xxx links to DiagnosticSignWarn
		CocWarningSign({ DiagnosticSignWarn }), -- CocWarningSign xxx links to DiagnosticSignWarn
		DiagnosticSignInfo({ fg = "#6099c0" }), -- DiagnosticSignInfo xxx guifg=#6099c0
		SnacksNotifierIconInfo({ DiagnosticSignInfo }), -- SnacksNotifierIconInfo xxx links to DiagnosticSignInfo
		CocInfoSign({ DiagnosticSignInfo }), -- CocInfoSign    xxx links to DiagnosticSignInfo
		DiagnosticSignHint({ fg = "#b279a7" }), -- DiagnosticSignHint xxx guifg=#b279a7
		CocHintSign({ DiagnosticSignHint }), -- CocHintSign    xxx links to DiagnosticSignHint
		DiagnosticSignOk({ fg = "#819b69" }), -- DiagnosticSignOk xxx guifg=#819b69
		Comment({ fg = "#686868", gui = "italic" }), -- Comment        xxx cterm=italic gui=italic guifg=#686868
		sym("@comment")({ Comment }), -- @comment       xxx links to Comment
		LazyComment({ Comment }), -- LazyComment    xxx links to Comment
		SnacksPickerLink({ Comment }), -- SnacksPickerLink xxx links to Comment
		SnacksPickerComment({ Comment }), -- SnacksPickerComment xxx links to Comment
		SnacksPickerDesc({ Comment }), -- SnacksPickerDesc xxx links to Comment
		SnacksPickerDiagnosticSource({ Comment }), -- SnacksPickerDiagnosticSource xxx links to Comment
		TroubleDiagnosticsCode({ Comment }), -- TroubleDiagnosticsCode xxx links to Comment
		TroubleDiagnosticsItemSource({ Comment }), -- TroubleDiagnosticsItemSource xxx links to Comment
		sym("@constant")({ fg = "#9e9e9e", gui = "bold" }), -- @constant      xxx cterm=bold gui=bold guifg=#9e9e9e
		sym("@lsp.type.enumMember")({ sym("@constant") }), -- @lsp.type.enumMember xxx links to @constant
		sym("@lsp.typemod.variable.static")({ sym("@constant") }), -- @lsp.typemod.variable.static xxx links to @constant
		SnacksPickerIconObject({ sym("@constant") }), -- SnacksPickerIconObject xxx links to @constant
		SnacksPickerIconConstant({ sym("@constant") }), -- SnacksPickerIconConstant xxx links to @constant
		SnacksPickerIconSource({ sym("@constant") }), -- SnacksPickerIconSource xxx links to @constant
		TroubleIconConstant({ sym("@constant") }), -- TroubleIconConstant xxx links to @constant
		TroubleIconObject({ sym("@constant") }), -- TroubleIconObject xxx links to @constant
		String({ fg = "#8b8b8b", gui = "italic" }), -- String         xxx cterm=italic gui=italic guifg=#8b8b8b
		sym("@string")({ String }), -- @string        xxx links to String
		NvimString({ String }), -- NvimString     xxx links to String
		SnacksPickerAuPattern({ String }), -- SnacksPickerAuPattern xxx links to String
		SnacksPickerRow({ String }), -- SnacksPickerRow xxx links to String
		Identifier({ fg = "#9e9e9e" }), -- Identifier     xxx guifg=#9e9e9e
		sym("@variable")({ Identifier }), -- @variable      xxx links to Identifier
		sym("@property")({ Identifier }), -- @property      xxx links to Identifier
		NvimIdentifier({ Identifier }), -- NvimIdentifier xxx links to Identifier
		WhichKeyDesc({ Identifier }), -- WhichKeyDesc   xxx links to Identifier
		sym("@string.special.symbol")({ Identifier }), -- @string.special.symbol xxx links to Identifier
		LazyReasonImport({ Identifier }), -- LazyReasonImport xxx links to Identifier
		Function({ fg = "#bbbbbb" }), -- Function       xxx guifg=#bbbbbb
		sym("@function")({ Function }), -- @function      xxx links to Function
		TroubleNormal({ Function }), -- TroubleNormal  xxx links to Function
		TroubleText({ Function }), -- TroubleText    xxx links to Function
		MiniIconsAzure({ Function }), -- MiniIconsAzure xxx links to Function
		SnacksPickerCmd({ Function }), -- SnacksPickerCmd xxx links to Function
		WhichKeyIconAzure({ Function }), -- WhichKeyIconAzure xxx links to Function
		SnacksWinKeyDesc({ Function }), -- SnacksWinKeyDesc xxx links to Function
		Operator({ fg = "nvimlightgrey2" }), -- Operator       xxx guifg=NvimLightGrey2
		NvimAssignment({ Operator }), -- NvimAssignment xxx links to Operator
		NvimOperator({ Operator }), -- NvimOperator   xxx links to Operator
		LazyReasonCmd({ Operator }), -- LazyReasonCmd  xxx links to Operator
		Delimiter({ fg = "#7c7c7c" }), -- Delimiter      xxx guifg=#7c7c7c
		sym("@punctuation")({ Delimiter }), -- @punctuation   xxx links to Delimiter
		sym("@punctuation.special")({ Delimiter }), -- @punctuation.special xxx links to Delimiter
		NvimParenthesis({ Delimiter }), -- NvimParenthesis xxx links to Delimiter
		NvimColon({ Delimiter }), -- NvimColon      xxx links to Delimiter
		NvimComma({ Delimiter }), -- NvimComma      xxx links to Delimiter
		NvimArrow({ Delimiter }), -- NvimArrow      xxx links to Delimiter
		sym("@punctuation.bracket")({ Delimiter }), -- @punctuation.bracket xxx links to Delimiter
		sym("@constructor.lua")({ Delimiter }), -- @constructor.lua xxx links to Delimiter
		sym("@tag.delimiter")({ Delimiter }), -- @tag.delimiter xxx links to Delimiter
		sym("@punctuation.delimiter")({ Delimiter }), -- @punctuation.delimiter xxx links to Delimiter
		markdownLinkTextDelimiter({ Delimiter }), -- markdownLinkTextDelimiter xxx links to Delimiter
		SnacksPickerDelim({ Delimiter }), -- SnacksPickerDelim xxx links to Delimiter
		Todo({ gui = "bold,underline" }), -- Todo           xxx cterm=bold,underline gui=bold,underline
		sym("@comment.todo")({ Todo }), -- @comment.todo  xxx links to Todo
		sym("@markup.strikethrough")({ gui = "strikethrough" }), -- @markup.strikethrough xxx cterm=strikethrough gui=strikethrough
		Added({ fg = "nvimlightgreen" }), -- Added          xxx ctermfg=10 guifg=NvimLightGreen
		SnacksPickerUndoAdded({ Added }), -- SnacksPickerUndoAdded xxx links to Added
		SnacksPickerGitStatusAdded({ Added }), -- SnacksPickerGitStatusAdded xxx links to Added
		Removed({ fg = "nvimlightred" }), -- Removed        xxx ctermfg=9 guifg=NvimLightRed
		SnacksPickerUndoRemoved({ Removed }), -- SnacksPickerUndoRemoved xxx links to Removed
		SnacksPickerGitStatusDeleted({ Removed }), -- SnacksPickerGitStatusDeleted xxx links to Removed
		Changed({ fg = "nvimlightcyan" }), -- Changed        xxx ctermfg=14 guifg=NvimLightCyan
		sym("@markup.heading.1.delimiter.vimdoc")({ fg = "bg", bg = "bg", sp = "fg", gui = "underdouble,nocombine" }), -- @markup.heading.1.delimiter.vimdoc xxx cterm=underdouble,nocombine gui=underdouble,nocombine guifg=bg guibg=bg guisp=fg
		sym("@markup.heading.2.delimiter.vimdoc")({ fg = "bg", bg = "bg", sp = "fg", gui = "underline,nocombine" }), -- @markup.heading.2.delimiter.vimdoc xxx cterm=underline,nocombine gui=underline,nocombine guifg=bg guibg=bg guisp=fg
		FloatShadow({ bg = "nvimdarkgrey4", blend = 80 }), -- FloatShadow    xxx ctermbg=0 guibg=NvimDarkGrey4 blend=80
		FloatShadowThrough({ bg = "nvimdarkgrey4", blend = 100 }), -- FloatShadowThrough xxx ctermbg=0 guibg=NvimDarkGrey4 blend=100
		RedrawDebugClear({ bg = "nvimdarkyellow" }), -- RedrawDebugClear xxx ctermfg=0 ctermbg=11 guibg=NvimDarkYellow
		RedrawDebugComposed({ bg = "nvimdarkgreen" }), -- RedrawDebugComposed xxx ctermfg=0 ctermbg=10 guibg=NvimDarkGreen
		RedrawDebugRecompose({ bg = "nvimdarkred" }), -- RedrawDebugRecompose xxx ctermfg=0 ctermbg=9 guibg=NvimDarkRed
		Error({ fg = "#de6e7c" }), -- Error          xxx guifg=#de6e7c
		ErrorMsg({ Error }), -- ErrorMsg       xxx links to Error
		DiagnosticError({ Error }), -- DiagnosticError xxx links to Error
		sym("@comment.error")({ Error }), -- @comment.error xxx links to Error
		NvimInvalid({ Error }), -- NvimInvalid    xxx links to Error
		MasonError({ Error }), -- MasonError     xxx links to Error
		SnacksPickerGitBreaking({ Error }), -- SnacksPickerGitBreaking xxx links to Error
		DiagnosticUnderlineError({ sp = "#de6e7c", gui = "undercurl" }), -- DiagnosticUnderlineError xxx cterm=undercurl gui=undercurl guisp=#de6e7c
		CocErrorHighlight({ DiagnosticUnderlineError }), -- CocErrorHighlight xxx links to DiagnosticUnderlineError
		DiagnosticUnderlineWarn({ sp = "#b77e64", gui = "undercurl" }), -- DiagnosticUnderlineWarn xxx cterm=undercurl gui=undercurl guisp=#b77e64
		CocWarningHighlight({ DiagnosticUnderlineWarn }), -- CocWarningHighlight xxx links to DiagnosticUnderlineWarn
		DiagnosticUnderlineInfo({ sp = "#6099c0", gui = "undercurl" }), -- DiagnosticUnderlineInfo xxx cterm=undercurl gui=undercurl guisp=#6099c0
		CocInfoHighlight({ DiagnosticUnderlineInfo }), -- CocInfoHighlight xxx links to DiagnosticUnderlineInfo
		DiagnosticUnderlineHint({ sp = "#b279a7", gui = "undercurl" }), -- DiagnosticUnderlineHint xxx cterm=undercurl gui=undercurl guisp=#b279a7
		CocHintHighlight({ DiagnosticUnderlineHint }), -- CocHintHighlight xxx links to DiagnosticUnderlineHint
		DiagnosticUnderlineOk({ sp = "#819b69", gui = "undercurl" }), -- DiagnosticUnderlineOk xxx cterm=undercurl gui=undercurl guisp=#819b69
		NvimInternalError({ fg = "red", bg = "red" }), -- NvimInternalError xxx ctermfg=9 ctermbg=9 guifg=Red guibg=Red
		NvimFigureBrace({ NvimInternalError }), -- NvimFigureBrace xxx links to NvimInternalError
		NvimSingleQuotedUnknownEscape({ NvimInternalError }), -- NvimSingleQuotedUnknownEscape xxx links to NvimInternalError
		NvimInvalidSingleQuotedUnknownEscape({ NvimInternalError }), -- NvimInvalidSingleQuotedUnknownEscape xxx links to NvimInternalError
		diffIndexLine({ fg = "#b77e64" }), -- diffIndexLine  xxx guifg=#b77e64
		diffLine({ fg = "#b279a7", gui = "bold" }), -- diffLine       xxx cterm=bold gui=bold guifg=#b279a7
		diffFile({ fg = "#b77e64", gui = "bold" }), -- diffFile       xxx cterm=bold gui=bold guifg=#b77e64
		diffNewFile({ fg = "#819b69", gui = "italic" }), -- diffNewFile    xxx cterm=italic gui=italic guifg=#819b69
		diffOldFile({ fg = "#de6e7c", gui = "italic" }), -- diffOldFile    xxx cterm=italic gui=italic guifg=#de6e7c
		Italic({ gui = "italic" }), -- Italic         xxx cterm=italic gui=italic
		sym("@markup.italic")({ Italic }), -- @markup.italic xxx links to Italic
		LazyCommitScope({ Italic }), -- LazyCommitScope xxx links to Italic
		sym("@markup.italic.markdown")({ Italic }), -- @markup.italic.markdown xxx links to Italic
		SnacksPickerItalic({ Italic }), -- SnacksPickerItalic xxx links to Italic
		SnacksPickerGitScope({ Italic }), -- SnacksPickerGitScope xxx links to Italic
		GitSignsDelete({ fg = "#de6e7c" }), -- GitSignsDelete xxx guifg=#de6e7c
		GitGutterDelete({ GitSignsDelete }), -- GitGutterDelete xxx links to GitSignsDelete
		GitSignsChange({ fg = "#6099c0" }), -- GitSignsChange xxx guifg=#6099c0
		GitGutterChange({ GitSignsChange }), -- GitGutterChange xxx links to GitSignsChange
		GitSignsAdd({ fg = "#819b69" }), -- GitSignsAdd    xxx guifg=#819b69
		GitGutterAdd({ GitSignsAdd }), -- GitGutterAdd   xxx links to GitSignsAdd
		FlashLabel({ fg = "#bbbbbb", bg = "#315167" }), -- FlashLabel     xxx guifg=#bbbbbb guibg=#315167
		FlashBackdrop({ fg = "#686868" }), -- FlashBackdrop  xxx guifg=#686868
		SnacksBackdrop({ bg = "#000000" }), -- SnacksBackdrop xxx guibg=#000000
		Bold({ gui = "bold" }), -- Bold           xxx cterm=bold gui=bold
		sym("@markup.strong")({ Bold }), -- @markup.strong xxx links to Bold
		LazyH2({ Bold }), -- LazyH2         xxx links to Bold
		SnacksPickerBold({ Bold }), -- SnacksPickerBold xxx links to Bold
		LeapBackdrop({ fg = "#444444", gui = "nocombine" }), -- LeapBackdrop   xxx cterm=nocombine gui=nocombine guifg=#444444
		LeapLabel({ fg = "#f268db", gui = "bold" }), -- LeapLabel      xxx cterm=bold gui=bold guifg=#f268db
		LeapMatch({ gui = "bold,underline,nocombine" }), -- LeapMatch      xxx cterm=bold,underline,nocombine gui=bold,underline,nocombine
		NvimTreeSpecialFile({ fg = "#b279a7", gui = "underline" }), -- NvimTreeSpecialFile xxx cterm=underline gui=underline guifg=#b279a7
		NvimTreeSymlink({ fg = "#6099c0" }), -- NvimTreeSymlink xxx guifg=#6099c0
		NvimTreeRootFolder({ fg = "#6099c0", gui = "bold" }), -- NvimTreeRootFolder xxx cterm=bold gui=bold guifg=#6099c0
		NvimTreeWinSeparator({ fg = "bg" }), -- NvimTreeWinSeparator xxx guifg=bg
		NnnWinSeparator({ NvimTreeWinSeparator }), -- NnnWinSeparator xxx links to NvimTreeWinSeparator
		NvimTreeNormal({ fg = "#bbbbbb", bg = "#1f1f1f" }), -- NvimTreeNormal xxx guifg=#bbbbbb guibg=#1f1f1f
		NnnNormal({ NvimTreeNormal }), -- NnnNormal      xxx links to NvimTreeNormal
		NeogitHunkHeaderHighlight({ fg = "#bbbbbb", bg = "#222222", gui = "bold" }), -- NeogitHunkHeaderHighlight xxx cterm=bold gui=bold guifg=#bbbbbb guibg=#222222
		CmpItemAbbrMatchFuzzy({ fg = "#a6a6a6", gui = "bold" }), -- CmpItemAbbrMatchFuzzy xxx cterm=bold gui=bold guifg=#a6a6a6
		CmpItemAbbrMatch({ fg = "#bbbbbb", gui = "bold" }), -- CmpItemAbbrMatch xxx cterm=bold gui=bold guifg=#bbbbbb
		CmpItemMenu({ fg = "#7f7f7f" }), -- CmpItemMenu    xxx guifg=#7f7f7f
		CmpItemKind({ fg = "#8b8b8b" }), -- CmpItemKind    xxx guifg=#8b8b8b
		CmpItemAbbrDeprecated({ fg = "#686868" }), -- CmpItemAbbrDeprecated xxx guifg=#686868
		CmpItemAbbr({ fg = "#9e9e9e" }), -- CmpItemAbbr    xxx guifg=#9e9e9e
		FzfLuaHeaderText({ fg = "#b77e64" }), -- FzfLuaHeaderText xxx guifg=#b77e64
		FzfLuaHeaderBind({ fg = "#819b69" }), -- FzfLuaHeaderBind xxx guifg=#819b69
		markdownLinkText({ fg = "#9e9e9e", gui = "underline" }), -- markdownLinkText xxx cterm=underline gui=underline guifg=#9e9e9e
		RenderMarkdownCode({ bg = "#222222" }), -- RenderMarkdownCode xxx guibg=#222222
		TelescopeMatching({ fg = "#b279a7", gui = "bold" }), -- TelescopeMatching xxx cterm=bold gui=bold guifg=#b279a7
		TelescopeSelectionCaret({ fg = "#de6e7c", bg = "#222222" }), -- TelescopeSelectionCaret xxx guifg=#de6e7c guibg=#222222
		TelescopeBorder({ fg = "#797979" }), -- TelescopeBorder xxx guifg=#797979
		FzfLuaBufFlagCur({ fg = "#b77e64" }), -- FzfLuaBufFlagCur xxx guifg=#b77e64
		BlinkCmpKind({ fg = "#8b8b8b" }), -- BlinkCmpKind   xxx guifg=#8b8b8b
		BlinkCmpKindOperator({ BlinkCmpKind }), -- BlinkCmpKindOperator xxx links to BlinkCmpKind
		BlinkCmpKindEvent({ BlinkCmpKind }), -- BlinkCmpKindEvent xxx links to BlinkCmpKind
		BlinkCmpKindStruct({ BlinkCmpKind }), -- BlinkCmpKindStruct xxx links to BlinkCmpKind
		BlinkCmpKindConstant({ BlinkCmpKind }), -- BlinkCmpKindConstant xxx links to BlinkCmpKind
		BlinkCmpKindEnumMember({ BlinkCmpKind }), -- BlinkCmpKindEnumMember xxx links to BlinkCmpKind
		BlinkCmpKindFolder({ BlinkCmpKind }), -- BlinkCmpKindFolder xxx links to BlinkCmpKind
		BlinkCmpKindReference({ BlinkCmpKind }), -- BlinkCmpKindReference xxx links to BlinkCmpKind
		BlinkCmpKindFile({ BlinkCmpKind }), -- BlinkCmpKindFile xxx links to BlinkCmpKind
		BlinkCmpKindColor({ BlinkCmpKind }), -- BlinkCmpKindColor xxx links to BlinkCmpKind
		BlinkCmpKindSnippet({ BlinkCmpKind }), -- BlinkCmpKindSnippet xxx links to BlinkCmpKind
		BlinkCmpKindModule({ BlinkCmpKind }), -- BlinkCmpKindModule xxx links to BlinkCmpKind
		BlinkCmpKindInterface({ BlinkCmpKind }), -- BlinkCmpKindInterface xxx links to BlinkCmpKind
		BlinkCmpKindClass({ BlinkCmpKind }), -- BlinkCmpKindClass xxx links to BlinkCmpKind
		BlinkCmpKindVariable({ BlinkCmpKind }), -- BlinkCmpKindVariable xxx links to BlinkCmpKind
		BlinkCmpKindField({ BlinkCmpKind }), -- BlinkCmpKindField xxx links to BlinkCmpKind
		BlinkCmpKindConstructor({ BlinkCmpKind }), -- BlinkCmpKindConstructor xxx links to BlinkCmpKind
		BlinkCmpKindFunction({ BlinkCmpKind }), -- BlinkCmpKindFunction xxx links to BlinkCmpKind
		BlinkCmpKindText({ BlinkCmpKind }), -- BlinkCmpKindText xxx links to BlinkCmpKind
		BlinkCmpKindUnit({ BlinkCmpKind }), -- BlinkCmpKindUnit xxx links to BlinkCmpKind
		BlinkCmpKindProperty({ BlinkCmpKind }), -- BlinkCmpKindProperty xxx links to BlinkCmpKind
		BlinkCmpKindTypeParameter({ BlinkCmpKind }), -- BlinkCmpKindTypeParameter xxx links to BlinkCmpKind
		BlinkCmpKindKeyword({ BlinkCmpKind }), -- BlinkCmpKindKeyword xxx links to BlinkCmpKind
		BlinkCmpKindValue({ BlinkCmpKind }), -- BlinkCmpKindValue xxx links to BlinkCmpKind
		BlinkCmpKindEnum({ BlinkCmpKind }), -- BlinkCmpKindEnum xxx links to BlinkCmpKind
		BlinkCmpKindMethod({ BlinkCmpKind }), -- BlinkCmpKindMethod xxx links to BlinkCmpKind
		MasonMutedBlockBold({ fg = "#191919", bg = "#8b8b8b", gui = "bold" }), -- MasonMutedBlockBold xxx cterm=bold gui=bold guifg=#191919 guibg=#8b8b8b
		MasonMutedBlock({ fg = "#191919", bg = "#8b8b8b" }), -- MasonMutedBlock xxx guifg=#191919 guibg=#8b8b8b
		MasonMuted({ fg = "#8b8b8b" }), -- MasonMuted     xxx guifg=#8b8b8b
		MasonHighlightBlockBoldSecondary({ fg = "#191919", bg = "#b77e64", gui = "bold" }), -- MasonHighlightBlockBoldSecondary xxx cterm=bold gui=bold guifg=#191919 guibg=#b77e64
		MasonHighlightBlockSecondary({ fg = "#191919", bg = "#b77e64" }), -- MasonHighlightBlockSecondary xxx guifg=#191919 guibg=#b77e64
		MasonHighlightSecondary({ fg = "#b77e64" }), -- MasonHighlightSecondary xxx guifg=#b77e64
		MasonHighlightBlockBold({ fg = "#191919", bg = "#6099c0", gui = "bold" }), -- MasonHighlightBlockBold xxx cterm=bold gui=bold guifg=#191919 guibg=#6099c0
		MasonHighlight({ fg = "#6099c0" }), -- MasonHighlight xxx guifg=#6099c0
		MasonHeader({ fg = "#191919", bg = "#b77e64", gui = "bold" }), -- MasonHeader    xxx cterm=bold gui=bold guifg=#191919 guibg=#b77e64
		FzfLuaLiveSym({ fg = "#b77e64" }), -- FzfLuaLiveSym  xxx guifg=#b77e64
		FzfLuaBufFlagAlt({ fg = "#6099c0" }), -- FzfLuaBufFlagAlt xxx guifg=#6099c0
		FzfLuaBufNr({ fg = "#819b69" }), -- FzfLuaBufNr    xxx guifg=#819b69
		MasonHighlightBlock({ fg = "#191919", bg = "#6099c0" }), -- MasonHighlightBlock xxx guifg=#191919 guibg=#6099c0
		SnacksPickerMatch({ fg = "#b279a7", gui = "bold" }), -- SnacksPickerMatch xxx cterm=bold gui=bold guifg=#b279a7
		SnacksIndentScope({ fg = "#444444" }), -- SnacksIndentScope xxx guifg=#444444
		SnacksIndent({ fg = "#282828" }), -- SnacksIndent   xxx guifg=#282828
		sym("@markup.quote")({ fg = "#8b8b8b" }), -- @markup.quote  xxx guifg=#8b8b8b
		FzfLuaTabMarker({ fg = "#819b69" }), -- FzfLuaTabMarker xxx guifg=#819b69
		FzfLuaTabTitle({ fg = "#66a5ad" }), -- FzfLuaTabTitle xxx guifg=#66a5ad
		FzfLuaFzfMatch({ fg = "#b279a7", gui = "bold" }), -- FzfLuaFzfMatch xxx cterm=bold gui=bold guifg=#b279a7
		FzfLuaPathColNr({ fg = "#969696", gui = "bold" }), -- FzfLuaPathColNr xxx cterm=bold gui=bold guifg=#969696
		FzfLuaPathLineNr({ FzfLuaPathColNr }), -- FzfLuaPathLineNr xxx links to FzfLuaPathColNr
		IblScope({ fg = "#444444" }), -- IblScope       xxx guifg=#444444
		IndentLineCurrent({ IblScope }), -- IndentLineCurrent xxx links to IblScope
		IblIndent({ fg = "#282828" }), -- IblIndent      xxx guifg=#282828
		IndentLine({ IblIndent }), -- IndentLine     xxx links to IblIndent
		NoiceFormatProgressDone({ fg = "#bbbbbb", bg = "#65435e" }), -- NoiceFormatProgressDone xxx guifg=#bbbbbb guibg=#65435e
		NoiceCmdlineIcon({ fg = "#6099c0" }), -- NoiceCmdlineIcon xxx guifg=#6099c0
		NoiceConfirmBorder({ NoiceCmdlineIcon }), -- NoiceConfirmBorder xxx links to NoiceCmdlineIcon
		NoiceCmdlinePopupBorder({ NoiceCmdlineIcon }), -- NoiceCmdlinePopupBorder xxx links to NoiceCmdlineIcon
		NoiceCmdlinePopupTitle({ NoiceCmdlineIcon }), -- NoiceCmdlinePopupTitle xxx links to NoiceCmdlineIcon
		NoiceCmdlineIconCmdline({ NoiceCmdlineIcon }), -- NoiceCmdlineIconCmdline xxx links to NoiceCmdlineIcon
		NoiceCmdlineIconInput({ NoiceCmdlineIcon }), -- NoiceCmdlineIconInput xxx links to NoiceCmdlineIcon
		NoiceCmdlineIconCalculator({ NoiceCmdlineIcon }), -- NoiceCmdlineIconCalculator xxx links to NoiceCmdlineIcon
		NoiceCmdlineIconHelp({ NoiceCmdlineIcon }), -- NoiceCmdlineIconHelp xxx links to NoiceCmdlineIcon
		NoiceCmdlineIconFilter({ NoiceCmdlineIcon }), -- NoiceCmdlineIconFilter xxx links to NoiceCmdlineIcon
		NoiceCmdlineIconLua({ NoiceCmdlineIcon }), -- NoiceCmdlineIconLua xxx links to NoiceCmdlineIcon
		WhichKeySeparator({ fg = "#616161" }), -- WhichKeySeparator xxx guifg=#616161
		LazyItalic({ gui = "italic" }), -- LazyItalic     xxx cterm=italic gui=italic
		LazyBold({ gui = "bold" }), -- LazyBold       xxx cterm=bold gui=bold
		NoiceCompletionItemKindDefault({ fg = "#8b8b8b" }), -- NoiceCompletionItemKindDefault xxx guifg=#8b8b8b
		NoiceCompletionItemKindClass({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindClass xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindConstructor({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindConstructor xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindModule({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindModule xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindEnum({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindEnum xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindVariable({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindVariable xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindFile({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindFile xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindField({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindField xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindUnit({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindUnit xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindEnumMember({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindEnumMember xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindText({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindText xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindSnippet({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindSnippet xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindConstant({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindConstant xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindProperty({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindProperty xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindValue({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindValue xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindKeyword({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindKeyword xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindStruct({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindStruct xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindInterface({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindInterface xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindMethod({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindMethod xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindFunction({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindFunction xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindFolder({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindFolder xxx links to NoiceCompletionItemKindDefault
		NoiceCompletionItemKindColor({ NoiceCompletionItemKindDefault }), -- NoiceCompletionItemKindColor xxx links to NoiceCompletionItemKindDefault
		sym("@markup.link.markdown")({ fg = "#9e9e9e", gui = "underline" }), -- @markup.link.markdown xxx cterm=underline gui=underline guifg=#9e9e9e
		sym("@markup.link.vimdoc")({ fg = "#9e9e9e", gui = "underline" }), -- @markup.link.vimdoc xxx cterm=underline gui=underline guifg=#9e9e9e
		sym("@label.vimdoc")({ fg = "#969696", gui = "bold" }), -- @label.vimdoc  xxx cterm=bold gui=bold guifg=#969696
		sym("@lsp.type.unresolvedReference")({ sp = "#de6e7c", gui = "undercurl" }), -- @lsp.type.unresolvedReference xxx cterm=undercurl gui=undercurl guisp=#de6e7c
		helpHyperTextEntry({ fg = "#969696", gui = "bold" }), -- helpHyperTextEntry xxx cterm=bold gui=bold guifg=#969696
		helpHyperTextJump({ fg = "#9e9e9e", gui = "underline" }), -- helpHyperTextJump xxx cterm=underline gui=underline guifg=#9e9e9e
		SneakLabelMask({ fg = "#b279a7", bg = "#b279a7" }), -- SneakLabelMask xxx guifg=#b279a7 guibg=#b279a7
		HopNextKey({ fg = "#b279a7", gui = "bold,underline" }), -- HopNextKey     xxx cterm=bold,underline gui=bold,underline guifg=#b279a7
		HopNextKey1({ fg = "#66a5ad", gui = "bold,underline" }), -- HopNextKey1    xxx cterm=bold,underline gui=bold,underline guifg=#66a5ad
		HopNextKey2({ fg = "#6099c0" }), -- HopNextKey2    xxx guifg=#6099c0
		HopUnmatched({ fg = "#686868" }), -- HopUnmatched   xxx guifg=#686868
		BufferVisible({ fg = "#cfcfcf" }), -- BufferVisible  xxx guifg=#cfcfcf
		BufferVisibleSign({ fg = "#cfcfcf" }), -- BufferVisibleSign xxx guifg=#cfcfcf
		BufferVisibleIndex({ fg = "#cfcfcf" }), -- BufferVisibleIndex xxx guifg=#cfcfcf
		CocMarkdownLink({ fg = "#66a5ad", gui = "underline" }), -- CocMarkdownLink xxx cterm=underline gui=underline guifg=#66a5ad
		NvimTreeCursorLine({ bg = "#242424" }), -- NvimTreeCursorLine xxx guibg=#242424
		NvimTreeCursorColumn({ NvimTreeCursorLine }), -- NvimTreeCursorColumn xxx links to NvimTreeCursorLine
		BufferLineInfoDiagnostic({ fg = "#4e4e4e", bg = "#212121", sp = "#487290" }), -- BufferLineInfoDiagnostic xxx guifg=#4e4e4e guibg=#212121 guisp=#487290
		BufferLineInfoSelected({ fg = "#6099c0", bg = "#2c2c2c", sp = "#6099c0", gui = "bold,italic" }), -- BufferLineInfoSelected xxx cterm=bold,italic gui=bold,italic guifg=#6099c0 guibg=#2c2c2c guisp=#6099c0
		BufferLineInfoVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineInfoVisible xxx guifg=#686868 guibg=#282828
		BufferLineBufferVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineBufferVisible xxx guifg=#686868 guibg=#282828
		BufferLineWarningDiagnosticVisible({ fg = "#4e4e4e", bg = "#282828" }), -- BufferLineWarningDiagnosticVisible xxx guifg=#4e4e4e guibg=#282828
		BufferLineWarningDiagnostic({ fg = "#4e4e4e", bg = "#212121", sp = "#895e4b" }), -- BufferLineWarningDiagnostic xxx guifg=#4e4e4e guibg=#212121 guisp=#895e4b
		BufferLineWarningSelected({ fg = "#b77e64", bg = "#2c2c2c", sp = "#b77e64", gui = "bold,italic" }), -- BufferLineWarningSelected xxx cterm=bold,italic gui=bold,italic guifg=#b77e64 guibg=#2c2c2c guisp=#b77e64
		BufferLineWarningVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineWarningVisible xxx guifg=#686868 guibg=#282828
		BufferLineErrorDiagnosticSelected({ fg = "#a6525d", bg = "#2c2c2c", sp = "#a6525d", gui = "bold,italic" }), -- BufferLineErrorDiagnosticSelected xxx cterm=bold,italic gui=bold,italic guifg=#a6525d guibg=#2c2c2c guisp=#a6525d
		BufferLineErrorDiagnosticVisible({ fg = "#4e4e4e", bg = "#282828" }), -- BufferLineErrorDiagnosticVisible xxx guifg=#4e4e4e guibg=#282828
		BufferLineErrorDiagnostic({ fg = "#4e4e4e", bg = "#212121", sp = "#a6525d" }), -- BufferLineErrorDiagnostic xxx guifg=#4e4e4e guibg=#212121 guisp=#a6525d
		BufferLineErrorSelected({ fg = "#de6e7c", bg = "#2c2c2c", sp = "#de6e7c", gui = "bold,italic" }), -- BufferLineErrorSelected xxx cterm=bold,italic gui=bold,italic guifg=#de6e7c guibg=#2c2c2c guisp=#de6e7c
		BufferLineErrorVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineErrorVisible xxx guifg=#686868 guibg=#282828
		BufferLineNumbersSelected({ bg = "#2c2c2c", gui = "bold,italic" }), -- BufferLineNumbersSelected xxx cterm=bold,italic gui=bold,italic guibg=#2c2c2c
		BufferLineNumbersVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineNumbersVisible xxx guifg=#686868 guibg=#282828
		BufferLineCloseButtonSelected({ bg = "#2c2c2c" }), -- BufferLineCloseButtonSelected xxx guibg=#2c2c2c
		BufferLineCloseButtonVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineCloseButtonVisible xxx guifg=#686868 guibg=#282828
		BufferLineCloseButton({ fg = "#686868", bg = "#212121" }), -- BufferLineCloseButton xxx guifg=#686868 guibg=#212121
		BufferLineOffsetSeparator({ fg = "#616161", bg = "#181818" }), -- BufferLineOffsetSeparator xxx guifg=#616161 guibg=#181818
		BufferLineSeparatorSelected({ fg = "#181818", bg = "#2c2c2c" }), -- BufferLineSeparatorSelected xxx guifg=#181818 guibg=#2c2c2c
		BufferLineSeparatorVisible({ fg = "#181818", bg = "#282828" }), -- BufferLineSeparatorVisible xxx guifg=#181818 guibg=#282828
		BufferLineIndicatorSelected({ fg = "#191919", bg = "#2c2c2c" }), -- BufferLineIndicatorSelected xxx guifg=#191919 guibg=#2c2c2c
		BufferLineIndicatorVisible({ fg = "#282828", bg = "#282828" }), -- BufferLineIndicatorVisible xxx guifg=#282828 guibg=#282828
		BufferLineGroupSeparator({ fg = "#686868", bg = "#181818" }), -- BufferLineGroupSeparator xxx guifg=#686868 guibg=#181818
		BufferLineTruncMarker({ fg = "#686868", bg = "#181818" }), -- BufferLineTruncMarker xxx guifg=#686868 guibg=#181818
		BufferLineHint({ fg = "#686868", bg = "#212121", sp = "#b279a7" }), -- BufferLineHint xxx guifg=#686868 guibg=#212121 guisp=#b279a7
		BufferLineModified({ fg = "#8b8b8b", bg = "#212121" }), -- BufferLineModified xxx guifg=#8b8b8b guibg=#212121
		BufferLineInfoDiagnosticVisible({ fg = "#4e4e4e", bg = "#282828" }), -- BufferLineInfoDiagnosticVisible xxx guifg=#4e4e4e guibg=#282828
		BufferLineInfoDiagnosticSelected({ fg = "#487290", bg = "#2c2c2c", sp = "#487290", gui = "bold,italic" }), -- BufferLineInfoDiagnosticSelected xxx cterm=bold,italic gui=bold,italic guifg=#487290 guibg=#2c2c2c guisp=#487290
		BufferLineHintVisible({ fg = "#686868", bg = "#282828" }), -- BufferLineHintVisible xxx guifg=#686868 guibg=#282828
		BufferLinePick({ fg = "#de6e7c", bg = "#212121", gui = "bold,italic" }), -- BufferLinePick xxx cterm=bold,italic gui=bold,italic guifg=#de6e7c guibg=#212121
		BufferLineDuplicate({ fg = "#626262", bg = "#212121", gui = "italic" }), -- BufferLineDuplicate xxx cterm=italic gui=italic guifg=#626262 guibg=#212121
		BufferLineInfo({ fg = "#686868", bg = "#212121", sp = "#6099c0" }), -- BufferLineInfo xxx guifg=#686868 guibg=#212121 guisp=#6099c0
		BufferLineSeparator({ fg = "#181818", bg = "#212121" }), -- BufferLineSeparator xxx guifg=#181818 guibg=#212121
		BufferLineGroupLabel({ fg = "#181818", bg = "#686868" }), -- BufferLineGroupLabel xxx guifg=#181818 guibg=#686868
		BufferLineWarningDiagnosticSelected({ fg = "#895e4b", bg = "#2c2c2c", sp = "#895e4b", gui = "bold,italic" }), -- BufferLineWarningDiagnosticSelected xxx cterm=bold,italic gui=bold,italic guifg=#895e4b guibg=#2c2c2c guisp=#895e4b
		BufferLineWarning({ fg = "#686868", bg = "#212121", sp = "#b77e64" }), -- BufferLineWarning xxx guifg=#686868 guibg=#212121 guisp=#b77e64
		BufferLineBuffer({ fg = "#686868", bg = "#212121" }), -- BufferLineBuffer xxx guifg=#686868 guibg=#212121
		BufferLineBackground({ fg = "#686868", bg = "#212121" }), -- BufferLineBackground xxx guifg=#686868 guibg=#212121
		BufferLineNumbers({ fg = "#686868", bg = "#212121" }), -- BufferLineNumbers xxx guifg=#686868 guibg=#212121
		BufferLineTabClose({ fg = "#686868", bg = "#212121" }), -- BufferLineTabClose xxx guifg=#686868 guibg=#212121
		BufferLineDuplicateSelected({ fg = "#626262", bg = "#2c2c2c", gui = "italic" }), -- BufferLineDuplicateSelected xxx cterm=italic gui=italic guifg=#626262 guibg=#2c2c2c
		BufferLineTabSeparatorSelected({ fg = "#181818", bg = "#2c2c2c" }), -- BufferLineTabSeparatorSelected xxx guifg=#181818 guibg=#2c2c2c
		BufferLineError({ fg = "#686868", bg = "#212121", sp = "#de6e7c" }), -- BufferLineError xxx guifg=#686868 guibg=#212121 guisp=#de6e7c
		BufferLinePickVisible({ fg = "#de6e7c", bg = "#282828", gui = "bold,italic" }), -- BufferLinePickVisible xxx cterm=bold,italic gui=bold,italic guifg=#de6e7c guibg=#282828
		BufferLineDiagnostic({ fg = "#4e4e4e", bg = "#212121" }), -- BufferLineDiagnostic xxx guifg=#4e4e4e guibg=#212121
		BufferLinePickSelected({ fg = "#de6e7c", bg = "#2c2c2c", gui = "bold,italic" }), -- BufferLinePickSelected xxx cterm=bold,italic gui=bold,italic guifg=#de6e7c guibg=#2c2c2c
		BufferLineDuplicateVisible({ fg = "#626262", bg = "#282828", gui = "italic" }), -- BufferLineDuplicateVisible xxx cterm=italic gui=italic guifg=#626262 guibg=#282828
		BufferLineFill({ fg = "#686868", bg = "#181818" }), -- BufferLineFill xxx guifg=#686868 guibg=#181818
		BufferLineBufferSelected({ bg = "#2c2c2c", gui = "bold,italic" }), -- BufferLineBufferSelected xxx cterm=bold,italic gui=bold,italic guibg=#2c2c2c
		BufferLineModifiedSelected({ fg = "#8b8b8b", bg = "#2c2c2c" }), -- BufferLineModifiedSelected xxx guifg=#8b8b8b guibg=#2c2c2c
		BufferLineModifiedVisible({ fg = "#8b8b8b", bg = "#282828" }), -- BufferLineModifiedVisible xxx guifg=#8b8b8b guibg=#282828
		BufferLineDiagnosticSelected({ bg = "#2c2c2c", gui = "bold,italic" }), -- BufferLineDiagnosticSelected xxx cterm=bold,italic gui=bold,italic guibg=#2c2c2c
		BufferLineDiagnosticVisible({ fg = "#4e4e4e", bg = "#282828" }), -- BufferLineDiagnosticVisible xxx guifg=#4e4e4e guibg=#282828
		BufferLineHintDiagnosticSelected({ fg = "#855a7d", bg = "#2c2c2c", sp = "#855a7d", gui = "bold,italic" }), -- BufferLineHintDiagnosticSelected xxx cterm=bold,italic gui=bold,italic guifg=#855a7d guibg=#2c2c2c guisp=#855a7d
		BufferLineHintDiagnosticVisible({ fg = "#4e4e4e", bg = "#282828" }), -- BufferLineHintDiagnosticVisible xxx guifg=#4e4e4e guibg=#282828
		BufferLineHintDiagnostic({ fg = "#4e4e4e", bg = "#212121", sp = "#855a7d" }), -- BufferLineHintDiagnostic xxx guifg=#4e4e4e guibg=#212121 guisp=#855a7d
		BufferLineHintSelected({ fg = "#b279a7", bg = "#2c2c2c", sp = "#b279a7", gui = "bold,italic" }), -- BufferLineHintSelected xxx cterm=bold,italic gui=bold,italic guifg=#b279a7 guibg=#2c2c2c guisp=#b279a7
		BufferLineTabSeparator({ fg = "#181818", bg = "#212121" }), -- BufferLineTabSeparator xxx guifg=#181818 guibg=#212121
		BufferLineTabSelected({ fg = "#191919", bg = "#2c2c2c" }), -- BufferLineTabSelected xxx guifg=#191919 guibg=#2c2c2c
		BufferLineTab({ fg = "#686868", bg = "#212121" }), -- BufferLineTab  xxx guifg=#686868 guibg=#212121
		lualine_transparent({ fg = "#bbbbbb", bg = "#191919", gui = "nocombine" }), -- lualine_transparent xxx gui=nocombine guifg=#bbbbbb guibg=#191919
		lualine_a_insert({ fg = "#a3a3a3", bg = "#324757", gui = "bold,nocombine" }), -- lualine_a_insert xxx gui=bold,nocombine guifg=#a3a3a3 guibg=#324757
		lualine_a_normal({ fg = "#a3a3a3", bg = "#525252", gui = "bold,nocombine" }), -- lualine_a_normal xxx gui=bold,nocombine guifg=#a3a3a3 guibg=#525252
		lualine_c_normal({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_normal xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_b_normal({ fg = "#a3a3a3", bg = "#3e3e3e", gui = "nocombine" }), -- lualine_b_normal xxx gui=nocombine guifg=#a3a3a3 guibg=#3e3e3e
		lualine_a_replace({ fg = "#a3a3a3", bg = "#3e2225", gui = "bold,nocombine" }), -- lualine_a_replace xxx gui=bold,nocombine guifg=#a3a3a3 guibg=#3e2225
		lualine_a_inactive({ fg = "#cfcfcf", bg = "#242424", gui = "bold,nocombine" }), -- lualine_a_inactive xxx gui=bold,nocombine guifg=#cfcfcf guibg=#242424
		lualine_c_inactive({ fg = "#cfcfcf", bg = "#242424", gui = "nocombine" }), -- lualine_c_inactive xxx gui=nocombine guifg=#cfcfcf guibg=#242424
		lualine_b_inactive({ fg = "#cfcfcf", bg = "#242424", gui = "nocombine" }), -- lualine_b_inactive xxx gui=nocombine guifg=#cfcfcf guibg=#242424
		lualine_a_visual({ fg = "#a3a3a3", bg = "#404040", gui = "bold,nocombine" }), -- lualine_a_visual xxx gui=bold,nocombine guifg=#a3a3a3 guibg=#404040
		lualine_a_command({ fg = "#a3a3a3", bg = "#65435e", gui = "bold,nocombine" }), -- lualine_a_command xxx gui=bold,nocombine guifg=#a3a3a3 guibg=#65435e
		lualine_c_2_normal({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_2_normal xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_c_2_insert({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_2_insert xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_c_2_visual({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_2_visual xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_c_2_replace({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_2_replace xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_c_2_command({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_2_command xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_c_2_terminal({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_2_terminal xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_c_2_inactive({ fg = "#939393", bg = "#242424", gui = "nocombine" }), -- lualine_c_2_inactive xxx gui=nocombine guifg=#939393 guibg=#242424
		lualine_c_diagnostics_error_normal({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_error_normal xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_c_diagnostics_error_insert({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_error_insert xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_c_diagnostics_error_visual({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_error_visual xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_c_diagnostics_error_replace({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_error_replace xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_c_diagnostics_error_command({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_error_command xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_c_diagnostics_error_terminal({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_error_terminal xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_c_diagnostics_error_inactive({ fg = "#de6e7c", bg = "#242424", gui = "nocombine" }), -- lualine_c_diagnostics_error_inactive xxx gui=nocombine guifg=#de6e7c guibg=#242424
		lualine_c_diagnostics_warn_normal({ fg = "#b77e64", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_warn_normal xxx gui=nocombine guifg=#b77e64 guibg=#2a2a2a
		lualine_c_diagnostics_warn_insert({ fg = "#b77e64", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_warn_insert xxx gui=nocombine guifg=#b77e64 guibg=#2a2a2a
		lualine_c_diagnostics_warn_visual({ fg = "#b77e64", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_warn_visual xxx gui=nocombine guifg=#b77e64 guibg=#2a2a2a
		lualine_c_diagnostics_warn_replace({ fg = "#b77e64", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_warn_replace xxx gui=nocombine guifg=#b77e64 guibg=#2a2a2a
		lualine_c_diagnostics_warn_command({ fg = "#b77e64", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_warn_command xxx gui=nocombine guifg=#b77e64 guibg=#2a2a2a
		lualine_c_diagnostics_warn_terminal({ fg = "#b77e64", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_warn_terminal xxx gui=nocombine guifg=#b77e64 guibg=#2a2a2a
		lualine_c_diagnostics_warn_inactive({ fg = "#b77e64", bg = "#242424", gui = "nocombine" }), -- lualine_c_diagnostics_warn_inactive xxx gui=nocombine guifg=#b77e64 guibg=#242424
		lualine_c_diagnostics_info_normal({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_info_normal xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_c_diagnostics_info_insert({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_info_insert xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_c_diagnostics_info_visual({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_info_visual xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_c_diagnostics_info_replace({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_info_replace xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_c_diagnostics_info_command({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_info_command xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_c_diagnostics_info_terminal({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_info_terminal xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_c_diagnostics_info_inactive({ fg = "#6099c0", bg = "#242424", gui = "nocombine" }), -- lualine_c_diagnostics_info_inactive xxx gui=nocombine guifg=#6099c0 guibg=#242424
		lualine_c_diagnostics_hint_normal({ fg = "#b279a7", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_hint_normal xxx gui=nocombine guifg=#b279a7 guibg=#2a2a2a
		lualine_c_diagnostics_hint_insert({ fg = "#b279a7", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_hint_insert xxx gui=nocombine guifg=#b279a7 guibg=#2a2a2a
		lualine_c_diagnostics_hint_visual({ fg = "#b279a7", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_hint_visual xxx gui=nocombine guifg=#b279a7 guibg=#2a2a2a
		lualine_c_diagnostics_hint_replace({ fg = "#b279a7", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_hint_replace xxx gui=nocombine guifg=#b279a7 guibg=#2a2a2a
		lualine_c_diagnostics_hint_command({ fg = "#b279a7", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_hint_command xxx gui=nocombine guifg=#b279a7 guibg=#2a2a2a
		lualine_c_diagnostics_hint_terminal({ fg = "#b279a7", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_diagnostics_hint_terminal xxx gui=nocombine guifg=#b279a7 guibg=#2a2a2a
		lualine_c_diagnostics_hint_inactive({ fg = "#b279a7", bg = "#242424", gui = "nocombine" }), -- lualine_c_diagnostics_hint_inactive xxx gui=nocombine guifg=#b279a7 guibg=#242424
		lualine_x_13_normal({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_13_normal xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_x_13_insert({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_13_insert xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_x_13_visual({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_13_visual xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_x_13_replace({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_13_replace xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_x_13_command({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_13_command xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_x_13_terminal({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_13_terminal xxx gui=nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_x_13_inactive({ fg = "#bbbbbb", bg = "#242424", gui = "nocombine" }), -- lualine_x_13_inactive xxx gui=nocombine guifg=#bbbbbb guibg=#242424
		lualine_x_14_normal({ fg = "#8b8b8b", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_14_normal xxx gui=nocombine guifg=#8b8b8b guibg=#2a2a2a
		lualine_x_14_insert({ fg = "#8b8b8b", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_14_insert xxx gui=nocombine guifg=#8b8b8b guibg=#2a2a2a
		lualine_x_14_visual({ fg = "#8b8b8b", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_14_visual xxx gui=nocombine guifg=#8b8b8b guibg=#2a2a2a
		lualine_x_14_replace({ fg = "#8b8b8b", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_14_replace xxx gui=nocombine guifg=#8b8b8b guibg=#2a2a2a
		lualine_x_14_command({ fg = "#8b8b8b", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_14_command xxx gui=nocombine guifg=#8b8b8b guibg=#2a2a2a
		lualine_x_14_terminal({ fg = "#8b8b8b", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_14_terminal xxx gui=nocombine guifg=#8b8b8b guibg=#2a2a2a
		lualine_x_14_inactive({ fg = "#8b8b8b", bg = "#242424", gui = "nocombine" }), -- lualine_x_14_inactive xxx gui=nocombine guifg=#8b8b8b guibg=#242424
		lualine_x_15_normal({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_15_normal xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_15_insert({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_15_insert xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_15_visual({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_15_visual xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_15_replace({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_15_replace xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_15_command({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_15_command xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_15_terminal({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_15_terminal xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_15_inactive({ fg = "#939393", bg = "#242424", gui = "nocombine" }), -- lualine_x_15_inactive xxx gui=nocombine guifg=#939393 guibg=#242424
		lualine_x_16_normal({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_16_normal xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_16_insert({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_16_insert xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_16_visual({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_16_visual xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_16_replace({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_16_replace xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_16_command({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_16_command xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_16_terminal({ fg = "#939393", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_16_terminal xxx gui=nocombine guifg=#939393 guibg=#2a2a2a
		lualine_x_16_inactive({ fg = "#939393", bg = "#242424", gui = "nocombine" }), -- lualine_x_16_inactive xxx gui=nocombine guifg=#939393 guibg=#242424
		lualine_x_diff_added_normal({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_added_normal xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_x_diff_added_insert({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_added_insert xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_x_diff_added_visual({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_added_visual xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_x_diff_added_replace({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_added_replace xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_x_diff_added_command({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_added_command xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_x_diff_added_terminal({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_added_terminal xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_x_diff_added_inactive({ fg = "#819b69", bg = "#242424", gui = "nocombine" }), -- lualine_x_diff_added_inactive xxx gui=nocombine guifg=#819b69 guibg=#242424
		lualine_x_diff_modified_normal({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_modified_normal xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_x_diff_modified_insert({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_modified_insert xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_x_diff_modified_visual({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_modified_visual xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_x_diff_modified_replace({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_modified_replace xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_x_diff_modified_command({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_modified_command xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_x_diff_modified_terminal({ fg = "#6099c0", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_modified_terminal xxx gui=nocombine guifg=#6099c0 guibg=#2a2a2a
		lualine_x_diff_modified_inactive({ fg = "#6099c0", bg = "#242424", gui = "nocombine" }), -- lualine_x_diff_modified_inactive xxx gui=nocombine guifg=#6099c0 guibg=#242424
		lualine_x_diff_removed_normal({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_removed_normal xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_x_diff_removed_insert({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_removed_insert xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_x_diff_removed_visual({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_removed_visual xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_x_diff_removed_replace({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_removed_replace xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_x_diff_removed_command({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_removed_command xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_x_diff_removed_terminal({ fg = "#de6e7c", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_x_diff_removed_terminal xxx gui=nocombine guifg=#de6e7c guibg=#2a2a2a
		lualine_x_diff_removed_inactive({ fg = "#de6e7c", bg = "#242424", gui = "nocombine" }), -- lualine_x_diff_removed_inactive xxx gui=nocombine guifg=#de6e7c guibg=#242424
		NoiceHiddenCursor({ blend = 100, gui = "nocombine" }), -- NoiceHiddenCursor xxx cterm=nocombine gui=nocombine blend=100
		lualine_transitional_lualine_a_normal_to_lualine_b_normal({ fg = "#525252", bg = "#3e3e3e", gui = "nocombine" }), -- lualine_transitional_lualine_a_normal_to_lualine_b_normal xxx gui=nocombine guifg=#525252 guibg=#3e3e3e
		lualine_transitional_lualine_b_normal_to_lualine_c_normal({ fg = "#3e3e3e", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_transitional_lualine_b_normal_to_lualine_c_normal xxx gui=nocombine guifg=#3e3e3e guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_normal({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_normal xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_insert({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_insert xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_visual({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_visual xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_replace({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_replace xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_command({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_command xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_terminal({ fg = "#819b69", bg = "#2a2a2a", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_terminal xxx gui=nocombine guifg=#819b69 guibg=#2a2a2a
		lualine_c_filetype_MiniIconsGreen_inactive({ fg = "#819b69", bg = "#242424", gui = "nocombine" }), -- lualine_c_filetype_MiniIconsGreen_inactive xxx gui=nocombine guifg=#819b69 guibg=#242424
		lualine_c_5_LV_Bold_normal({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_normal xxx gui=bold,nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_c_5_LV_Bold_insert({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_insert xxx gui=bold,nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_c_5_LV_Bold_visual({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_visual xxx gui=bold,nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_c_5_LV_Bold_replace({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_replace xxx gui=bold,nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_c_5_LV_Bold_command({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_command xxx gui=bold,nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_c_5_LV_Bold_terminal({ fg = "#bbbbbb", bg = "#2a2a2a", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_terminal xxx gui=bold,nocombine guifg=#bbbbbb guibg=#2a2a2a
		lualine_c_5_LV_Bold_inactive({ fg = "#cfcfcf", bg = "#242424", gui = "bold,nocombine" }), -- lualine_c_5_LV_Bold_inactive xxx gui=bold,nocombine guifg=#cfcfcf guibg=#242424
		lualine_transitional_lualine_a_normal_to_lualine_c_filetype_MiniIconsGreen_normal({
			fg = "#525252",
			bg = "#2a2a2a",
			gui = "nocombine",
		}), -- lualine_transitional_lualine_a_normal_to_lualine_c_filetype_MiniIconsGreen_normal xxx gui=nocombine guifg=#525252 guibg=#2a2a2a
		lualine_transitional_lualine_b_normal_to_lualine_x_13_normal({
			fg = "#3e3e3e",
			bg = "#2a2a2a",
			gui = "nocombine",
		}), -- lualine_transitional_lualine_b_normal_to_lualine_x_13_normal xxx gui=nocombine guifg=#3e3e3e guibg=#2a2a2a
		BufferLineMiniIconsGreySelected({ bg = "#2c2c2c" }), -- BufferLineMiniIconsGreySelected xxx guibg=#2c2c2c
		lualine_transitional_lualine_a_insert_to_lualine_b_normal({ fg = "#324757", bg = "#3e3e3e", gui = "nocombine" }), -- lualine_transitional_lualine_a_insert_to_lualine_b_normal xxx gui=nocombine guifg=#324757 guibg=#3e3e3e
		lualine_transitional_lualine_b_normal_to_lualine_x_13_insert({
			fg = "#3e3e3e",
			bg = "#2a2a2a",
			gui = "nocombine",
		}), -- lualine_transitional_lualine_b_normal_to_lualine_x_13_insert xxx gui=nocombine guifg=#3e3e3e guibg=#2a2a2a
		lualine_transitional_lualine_a_command_to_lualine_b_normal({
			fg = "#65435e",
			bg = "#3e3e3e",
			gui = "nocombine",
		}), -- lualine_transitional_lualine_a_command_to_lualine_b_normal xxx gui=nocombine guifg=#65435e guibg=#3e3e3e
		lualine_transitional_lualine_b_normal_to_lualine_x_13_command({
			fg = "#3e3e3e",
			bg = "#2a2a2a",
			gui = "nocombine",
		}), -- lualine_transitional_lualine_b_normal_to_lualine_x_13_command xxx gui=nocombine guifg=#3e3e3e guibg=#2a2a2a
	}
end)
return theme
